
const NOTES = {
    65:{
        noteName:"./notes/a-3.mp3",
    },
    66:{
        noteName:"./notes/a-4.mp3",
    },
    67:{
        noteName:"./notes/a-5.mp3",
    },
    68:{
        noteName:"./notes/a3.mp3",
    },
    69:{
        noteName:"./notes/a4.mp3",
    },
    70:{
        noteName:"./notes/a5.mp3",
    },
    71:{
        noteName:"./notes/b3.mp3",
    },
    72:{
        noteName:"./notes/b4.mp3",
    },
    73:{
        noteName:"./notes/b5.mp3",
    },
    74:{
        noteName:"./notes/c-3.mp3",
    },
    75:{
        noteName:"./notes/c-4.mp3",
    },
    76:{
        noteName:"./notes/c-5.mp3",
    },
    77:{
        noteName:"./notes/c3.mp3",
    },
    78:{
        noteName:"./notes/c4.mp3",
    },
    79:{
        noteName:"./notes/c5.mp3",
    },
    80:{
        noteName:"./notes/c6.mp3",
    },
    81:{
        noteName:"./notes/d-3.mp3",
    },
    82:{
        noteName:"./notes/d-4.mp3",
    },
    83:{
        noteName:"./notes/d-5.mp3",
    },
    84:{
        noteName:"./notes/d3.mp3",
    },
    85:{
        noteName:"./notes/d4.mp3",
    },
    86:{
        noteName:"./notes/d5.mp3",
    },
    87:{
        noteName:"./notes/e3.mp3",
    },
    88:{
        noteName:"./notes/e4.mp3",
    },
    89:{
        noteName:"./notes/e5.mp3",
    },
    90:{
        noteName:"./notes/f-3.mp3",
    },
    48:{
        noteName:"./notes/f-4.mp3",
    },
    49:{
        noteName:"./notes/f-5.mp3",
    },
    50:{
        noteName:"./notes/f3.mp3",
    },
    51:{
        noteName:"./notes/f4.mp3",
    },
    52:{
        noteName:"./notes/f5.mp3",
    },
    53:{
        noteName:"./notes/g-3.mp3",
    },
    54:{
        noteName:"./notes/g-4.mp3",
    },
    55:{
        noteName:"./notes/g-5.mp3",
    },
    56:{
        noteName:"./notes/g3.mp3",
    },
    57:{
        noteName:"./notes/g4.mp3",
    },
};